Repository Caterinapiai/vino_view, pull requests merged in 2024-01, with the labels that each got.

#2 Uncomment Dockerfile
  backend/Dockerfile
  frontend/Dockerfile
Labels: enhancement

#4 Import datasets and create /top-wines endpoint
  backend/app/datasets/Red.csv
  backend/app/datasets/Rose.csv
  backend/app/datasets/Sparkling.csv
  backend/app/datasets/White.csv
  backend/app/employees.csv
  backend/app/main.py
  backend/app/mymodules/birthdays.py
  backend/app/mymodules/utils.py
  backend/tests/test_main.py
Labels: documentation

#6 Improve page structure
  frontend/app/main.py
  frontend/app/templates/base.html
  frontend/app/templates/index.html
Labels: documentation

#8 Create /most-recent-wines
  backend/app/main.py
  backend/app/mymodules/utils.py
Labels: enhancement

#10 Backend_endpoint
  backend/app/main.py
  backend/app/mymodules/utils.py
  frontend/app/main.py
  frontend/app/templates/index.html
Labels: enhancement

#13 Wines-by-type endpoint
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  backend/app/main.py
  backend/app/mymodules/utils.py
Labels: enhancement

#17 type filtering
  backend/app/mymodules/utils.py
  frontend/app/main.py
  frontend/app/templates/advanced-search.html
  frontend/app/templates/base.html
  frontend/app/templates/index.html
  frontend/app/templates/internal.html
Labels: bug

#19 Refactoring advanced
  backend/app/main.py
  backend/app/mymodules/filter_functions.py
  backend/app/mymodules/utils.py
Labels: enhancement

#21 Add documentation modules
  backend/app/mymodules/filter_functions.py
  backend/app/mymodules/utils.py
Labels: enhancement

#25 endpoint to get range of years
  backend/app/main.py
  backend/app/mymodules/utils.py
Labels: enhancement

#27 Refactoring and add comm.
  backend/app/main.py
  backend/app/mymodules/filter_functions.py
  backend/app/mymodules/utils.py
Labels: enhancement

#29 Semplify filters function
  backend/app/mymodules/filter_functions.py
  backend/app/mymodules/utils.py
Labels: bug

#31 Other advanced search + frontend refactoring
  backend/app/main.py
  backend/app/mymodules/utils.py
  frontend/app/constants.py
  frontend/app/counties.py
  frontend/app/fetch.py
  frontend/app/form.py
  frontend/app/main.py
  frontend/app/templates/advanced-search.html
  frontend/app/wine_types.py
Labels: enhancement

#33 PEP-8
  frontend/app/counties.py
  frontend/app/fetch.py
  frontend/app/form.py
  frontend/app/main.py
Labels: documentation

#35 Correction of a name
  frontend/app/countries.py
Labels: documentation

#37 Fix errors in homepage
  frontend/app/fetch.py
  frontend/app/templates/index.html
Labels: bug

#43 Create full coverage unit tests
  backend/Dockerfile
  backend/app/main.py
  backend/app/mymodules/filter_functions.py
  backend/app/mymodules/utils.py
  backend/tests/test_advanced_search.py
  backend/tests/test_main.py
Labels: enhancement

#47 Fix advanced research for ranges
  backend/app/main.py
  backend/app/mymodules/filter_functions.py
  backend/app/mymodules/utils.py
Labels: enhancement

#51 add README file
  README.md
Labels: documentation
